{
 "title": "PacketProber Dashboard",
 "tags": [
  "retina",
  "packetprober",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Active Probes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(networkobservability_probe_total)"
    }
   ]
  },
  {
   "title": "Loss % by Target",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (sum(rate(networkobservability_probe_failure_total[1m])) by (probe_name, endpoint, protocol) / sum(rate(networkobservability_probe_total[1m])) by (probe_name, endpoint, protocol))",
     "legendFormat": "{{probe_name}} ({{protocol}})"
    }
   ]
  },
  {
   "title": "Latency by Target (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "networkobservability_probe_latency_milliseconds",
     "legendFormat": "{{probe_name}} ({{protocol}})"
    }
   ]
  },
  {
   "title": "Failures by Error Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (error_type) (increase(networkobservability_probe_failure_total[1h]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Active Probe List",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "last_over_time(networkobservability_probe_total[5m])"
    }
   ]
  }
 ]
}